#!/usr/bin/env python3
"""Regenerate the per-directory README.md files.

GitHub renders a README.md inside any directory listing, so each data directory
explains itself when someone browses to it. These are generated rather than
hand-written so the counts, sizes and checksums cannot drift away from the files
they describe -- re-run this after any sweep or analysis.

    python folder_docs.py
"""

import hashlib
import json
import os
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.abspath(__file__))
TIER_ORDER = ["64MB", "256MB", "1GB", "4GB", "8GB"]
STAMP = ("<!-- generated by folder_docs.py -- edit that script, not this file -->")


def human(n):
    for unit in ("B", "KB", "MB", "GB"):
        if abs(n) < 1024 or unit == "GB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024


def size(path):
    return os.path.getsize(path) if os.path.exists(path) else 0


def write(rel, body):
    path = os.path.join(ROOT, rel, "README.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body.rstrip() + "\n\n" + STAMP + "\n")
    print(f"  wrote {rel}/README.md")


def load_results():
    d = os.path.join(ROOT, "results")
    per_file, rows = {}, {}
    if not os.path.isdir(d):
        return per_file, rows
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".jsonl"):
            continue
        rs = []
        with open(os.path.join(d, fn), encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    r = json.loads(line)
                    rs.append(r)
                    rows[(r["row_id"], r["corpus_tier"])] = r
        per_file[fn] = rs
    return per_file, rows


# --------------------------------------------------------------------------------

def doc_corpus():
    d = os.path.join(ROOT, "corpus")
    metas = []
    for fn in sorted(os.listdir(d)):
        if fn.endswith(".meta.json"):
            with open(os.path.join(d, fn), encoding="utf-8") as fh:
                m = json.load(fh)
            m["_file"] = fn.replace(".meta.json", ".txt")
            m["_present"] = os.path.exists(os.path.join(d, m["_file"]))
            metas.append(m)
    metas.sort(key=lambda m: TIER_ORDER.index(m["tier"])
               if m["tier"] in TIER_ORDER else 99)

    lines = ["# `corpus/` — the PG-19 corpus tiers", "",
             "Every measurement in this repository was taken against these files.",
             "",
             "**The `.txt` files themselves are not committed** — they total about "
             "5.3 GB. What *is* committed is one `.meta.json` per tier recording the "
             "byte count, document count and sha256, so a rebuilt corpus can be "
             "verified byte-for-byte against the one that produced the published "
             "results.", "",
             "## Tiers", "",
             "| tier | bytes | documents | sha256 (first 16) | on disk here |",
             "|---|---:|---:|---|---|"]
    for m in metas:
        lines.append(f"| `{m['_file']}` | {m['bytes']:,} | {m['documents']:,} | "
                     f"`{m['sha256'][:16]}…` | "
                     f"{'yes' if m['_present'] else 'no (gitignored)'} |")
    total = sum(m["bytes"] for m in metas)
    docs = max((m["documents"] for m in metas), default=0)
    seed = metas[0].get("shuffle_seed") if metas else None
    lines += ["",
              f"Total across tiers: **{human(total)}**, up to **{docs:,} documents** "
              f"in the largest.", "",
              "## How to rebuild", "", "```bash",
              'python build_corpus.py --tiers "64MB,256MB,1GB,4GB" --out ./corpus/',
              "python build_corpus.py --verify-only --tiers "
              '"64MB,256MB,1GB,4GB" --out ./corpus/',
              "```", "",
              "The builder is idempotent: a tier whose file and sha256 already match "
              "its `.meta.json` is skipped rather than refetched.", "",
              "## Why each tier is a standalone corpus", "",
              "Each file is cut at a **document boundary past its target size**, not "
              "truncated at an exact byte count. So a tier is a complete, valid "
              "corpus in its own right rather than a prefix of the next one, and no "
              "tier ends with half a book. Document order is shuffled once with a "
              f"fixed seed (`{seed}`) before accumulation, so the tiers are not "
              "correlated with publication date or any other dataset-native "
              "ordering — and the shuffle is reproducible.", "",
              "## Source", "",
              "`deepmind/pg19` (Apache 2.0) — Rae et al. 2019, *Compressive "
              "Transformers for Long-Range Sequence Modelling*, "
              "[arXiv:1911.05507](https://arxiv.org/abs/1911.05507).", "",
              "Note that `datasets.load_dataset(\"deepmind/pg19\", streaming=True)` "
              "**does not work** — the Hub repo carries only a loading script and "
              "file lists, has no parquet, and its `refs/convert/parquet` branch has "
              "no data either, while loading scripts were removed in `datasets` 3.0. "
              "`build_corpus.py` fetches the books directly from the public GCS "
              "bucket the script points at. See `../FINDINGS.md`."]
    write("corpus", "\n".join(lines))


def doc_results():
    per_file, rows = load_results()
    ok = [r for r in rows.values() if r.get("round_trip_verified")]
    bad = [r for r in rows.values() if not r.get("round_trip_verified")]

    lines = ["# `results/` — one JSON object per matrix cell", "",
             "Raw, append-only sweep output. Each line is one fully executed "
             "configuration: compressed **and** decompressed, with its sha256, byte "
             "length and token count checked against the archive footer.", ""]
    lines += [f"**{len(ok):,} of {len(rows):,} cells round-trip verified"
              + (f", {len(bad)} failed" if bad else ", 0 failed") + ".**", ""]

    lines += ["## Files", "",
              "| file | cells | tiers | verified |", "|---|---:|---|---:|"]
    for fn, rs in per_file.items():
        tiers = sorted({r["corpus_tier"] for r in rs},
                       key=lambda t: TIER_ORDER.index(t) if t in TIER_ORDER else 99)
        v = sum(1 for r in rs if r.get("round_trip_verified"))
        lines.append(f"| `{fn}` | {len(rs)} | {', '.join(tiers)} | {v} |")

    kinds = Counter(r["cell_kind"] for r in rows.values())
    lines += ["", "## Cell kinds", "",
              "| kind | cells | what it varies |", "|---|---:|---|"]
    why = {
        "ratio_grid": "the axes that determine ratio (tokenizer x packing x "
                      "backend), everything else held at baseline",
        "ofat_threads": "thread count only",
        "ofat_layout": "tokenization layout only",
        "ofat_transport": "subprocess CLI vs in-process binding only",
        "ofat_chunk_size": "chunk size only",
        "ofat_batch_chunks": "batch size only",
        "smoke": "single pre-flight configuration",
    }
    for k, n in sorted(kinds.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| `{k}` | {n} | {why.get(k, '-')} |")

    tot = sum((r.get("total_time_s") or 0) + (r.get("decompress_time_s") or 0)
              for r in ok)
    unsafe = sum(r.get("unsafe_boundary_cuts") or 0 for r in ok)
    lines += ["", f"Measured cell time across all verified cells: "
              f"**{tot / 3600:.1f} hours**. Chunks cut at a point with no "
              f"tokenizer-safe boundary: **{unsafe}**.", ""]

    lines += ["## Reading a row", "", "```bash",
              "# pretty-print the best-ratio cell at the 4GB tier",
              "python -c \"import json,sys; rs=[json.loads(l) for l in "
              "open('results/sweep_4gb.jsonl')]; \\",
              "  print(json.dumps(max(rs, key=lambda r: r['ratio']), indent=2))\"",
              "```", "",
              "Key fields beyond the obvious ones:", "",
              "| field | meaning |", "|---|---|",
              "| `row_id` | stable hash of the cell's parameters — the same cell has "
              "the same id across runs and machines, which is what makes resume and "
              "`rerun-cell` work |",
              "| `packed_bytes` | bytes actually handed to the compressor (the packed "
              "token stream). Not the corpus size and not the compressed output — "
              "this is the quantity that sets the `xz` block count |",
              "| `round_trip_verified` | **the gate.** False means the ratio on that "
              "row is not trustworthy and the analysis excludes it |",
              "| `unsafe_boundary_cuts` | chunks that had no tokenizer-safe cut point "
              "in the lookahead window. Non-zero means that row's token stream "
              "depends on chunk size |",
              "| `peak_rss_mb` | peak resident set of the cell's process tree, sampled "
              "by the parent. `null` if `psutil` was unavailable — never guessed |",
              "",
              "## Provenance note", "",
              "Rows are appended and fsynced as each cell finishes, so an interrupted "
              "sweep never loses completed work. A later row for the same "
              "`(row_id, corpus_tier)` supersedes an earlier one, which is how "
              "`matrix.py rerun-cell` corrections are applied without editing "
              "history. `analyze.py` de-duplicates on that key.", "",
              "Absolute paths are rewritten to repo-relative form by "
              "`../scrub_paths.py` before publication."]
    write("results", "\n".join(lines))


def doc_report():
    d = os.path.join(ROOT, "report")
    figs = {
        "ratio_gap_vs_corpus_size": (
            "**The central figure.** Ratio gap over raw bytes, as a percentage of "
            "the raw-backend ratio, versus corpus size. Rising means window "
            "expansion; flat means the gain is representation density; below zero "
            "means pre-tokenizing hurts."),
        "ratio_vs_corpus_size": (
            "Absolute compression ratio versus corpus size, one panel per backend, "
            "with raw bytes as the reference line in each."),
        "ratio_vs_throughput_pareto": (
            "Ratio against compression throughput at the 1GB tier, with the Pareto "
            "frontier — the configurations nothing else is both smaller *and* faster "
            "than. This is the figure to read if you are choosing a configuration."),
        "thread_scaling": (
            "Left: `xz -T` speedup against the number of blocks available, with the "
            "`speedup = blocks` line and the core-count ceiling. Right: what "
            "multithreading costs in ratio, per backend."),
        "packing_decomposition": (
            "Waterfall separating the two things bundled together in the "
            "`fixed_u16` result: how much comes from the fixed 2-byte width, and how "
            "much from the `lc=1,lp=1,pb=1` alignment tuning."),
    }
    lines = ["# `report/` — generated analysis", "",
             "Everything here is derived from `../results/` and is safe to delete; "
             "regenerate with:", "", "```bash",
             "python analyze.py --results ./results/ --out ./report/", "```", "",
             "## Tables", "",
             "| file | size | what it is |", "|---|---:|---|"]
    for fn, desc in (("summary.md", "Human-readable summary: per-tier best-ratio and "
                      "best-throughput tables kept separate, plus explicit numeric "
                      "answers to the four research questions. Rows that failed "
                      "round-trip verification are listed in their own section rather "
                      "than dropped quietly."),
                     ("results.csv", "Every result row flattened to CSV, for "
                      "spreadsheet or pandas use. This is the table-view twin of the "
                      "figures — no value is encoded by colour alone.")):
        p = os.path.join(d, fn)
        if os.path.exists(p):
            lines.append(f"| `{fn}` | {human(size(p))} | {desc} |")

    lines += ["", "## Figures", "",
              "Each figure is rendered twice: `<name>.png` for light surfaces and "
              "`<name>_dark.png` for dark ones. The dark variants are the same hues "
              "re-stepped for a dark surface, not an inversion — the README serves "
              "them via `<picture>` so they follow your GitHub theme.", "",
              "| figure | size | what it shows |", "|---|---:|---|"]
    for stem, desc in figs.items():
        p = os.path.join(d, stem + ".png")
        if os.path.exists(p):
            lines.append(f"| `{stem}.png` | {human(size(p))} | {desc} |")

    lines += ["", "## On the colours", "",
              "The categorical palette and its slot order are load-bearing rather "
              "than decorative: the order is what keeps adjacent series separable "
              "under colour-vision deficiency. Both palettes were checked with a "
              "validator, not eyeballed — 4 slots for line charts (worst adjacent "
              "CVD ΔE 9.1 light / 8.4 dark) and 3 for scatter, where every pair is "
              "effectively adjacent (worst all-pairs ΔE 9.2 light / 9.4 dark). "
              "Where more classes exist than the cap allows, the extra dimension "
              "moves to line style or grouping rather than to another hue. Corpus "
              "size and thread count are magnitudes, so where they are encoded by "
              "colour they use a single-hue ordinal ramp. See `../plots.py`."]
    write("report", "\n".join(lines))


def doc_logs():
    d = os.path.join(ROOT, "logs")
    if not os.path.isdir(d):
        return
    known = {
        "verify_boundaries.log": (
            "Output of the blocking chunk-boundary differential test: whole-stream "
            "tokenization versus split-and-concatenated, for all four tokenizers at "
            "1/2/4 MB chunks. **This is the evidence for the gate** — the sweep was "
            "not allowed to run until every combination came back token-identical "
            "with zero unsafe cuts."),
        "sweep_run.log": (
            "Full console transcript of the sweep programme: every cell, its ratio, "
            "throughput, peak RSS and wall time, plus the per-stage validity drop log "
            "and pre-flight estimates."),
        "build_corpus.log": (
            "Corpus construction transcript for the 256MB/1GB/4GB tiers, including "
            "fetch throughput and the per-tier checkpoint checksums."),
    }
    lines = ["# `logs/` — run provenance", "",
             "Raw transcripts, kept so the published numbers can be traced back to "
             "the run that produced them rather than taken on trust. Nothing here is "
             "an input to anything; all of it is a record.", "",
             "| file | lines | size | what it records |", "|---|---:|---:|---|"]
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".log"):
            continue
        p = os.path.join(d, fn)
        with open(p, encoding="utf-8", errors="replace") as fh:
            n = sum(1 for _ in fh)
        lines.append(f"| `{fn}` | {n:,} | {human(size(p))} | "
                     f"{known.get(fn, 'run output')} |")
    lines += ["", "Absolute paths were rewritten out of these before publication; "
              "they contain no operator home directories."]
    write("logs", "\n".join(lines))


def main():
    print("regenerating per-directory READMEs")
    doc_corpus()
    doc_results()
    doc_report()
    doc_logs()


if __name__ == "__main__":
    main()
